# workflow 名稱
name: Build

# 什麼情況下觸發 workflow
on:
  # 對於 main branch 建立 Branch 與 Pull Request 時觸發 workflow
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # 允許你從 Action 頁簽上手動執行 workflow
  workflow_dispatch:

# Job 可以循序或平行執行
jobs:
  # 這個 workflow 只有一個 job，名稱為 "build"
  build:
    # 這個 job 會執行在作業系統為 ubuntu 的 runner
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 設定 job 層級的環境變數

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Add .nojekyll file
        run: echo > build/client/.nojekyll

#       - name: Copy 404.html
#         run: cp build/client/index.html build/client/404.html

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./build/client
